# Generated by Django 4.1.3 on 2023-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_class_group_scheduleclass_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_lessons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='class',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
