# Generated by Django 4.1.3 on 2023-05-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_class_max_lessons_class_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(to='main.classroom'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(to='main.group'),
        ),
    ]
