# Generated by Django 4.1.3 on 2023-05-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testtable_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classrooms',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
    ]
