# Generated by Django 4.1.3 on 2023-05-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_teacher_classrooms_remove_teacher_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='duration',
        ),
    ]
