# Generated by Django 4.1.3 on 2023-05-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_class_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classrooms',
            field=models.ManyToManyField(blank=True, null=True, to='main.classroom'),
        ),
        migrations.AlterField(
            model_name='class',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='main.group'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
