# Generated by Django 4.1.3 on 2023-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_class_classrooms_alter_class_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='name',
        ),
        migrations.AddField(
            model_name='testtable',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
